Repository d-h-k/airbnb, pull requests merged in 2021-05, with the labels that each got.

#12 [BE] Dto 멤버 내용 추가
  BE/airbnb/src/main/java/com/example/airbnb/dto/AccommodationDTO.java
  BE/airbnb/src/main/java/com/example/airbnb/dto/LocationDTO.java
  BE/airbnb/src/main/java/com/example/airbnb/dto/RecommendedDTO.java
  BE/airbnb/src/main/java/com/example/airbnb/dto/ThemeDTO.java
Labels: 백엔드

#76 Fe/feature/75/match param
  FE/airbnb-fe/src/App.js
  FE/airbnb-fe/src/components/Atoms/Search/SearchBtn/index.jsx
  FE/airbnb-fe/src/components/Atoms/Search/index.jsx
  FE/airbnb-fe/src/components/Reservation/index.jsx
  FE/airbnb-fe/src/components/utils/reducer/calendarReducer.js
  FE/airbnb-fe/src/components/utils/reducer/peopleReducer.js
  FE/airbnb-fe/src/components/utils/reducer/priceReducer.js
Labels: 프론트엔드

#78 Fe/feature/77/res header
  FE/airbnb-fe/src/components/Atoms/Search/index.jsx
  FE/airbnb-fe/src/components/Atoms/icons/AccountIcon.jsx
  FE/airbnb-fe/src/components/Atoms/icons/AirbnbIcon.jsx
  FE/airbnb-fe/src/components/Atoms/icons/MenuIcon.jsx
  FE/airbnb-fe/src/components/Home/HeroSection/Header/AccountMenu/index.jsx
  FE/airbnb-fe/src/components/Home/HeroSection/Header/NavRadio/Activity.jsx
  FE/airbnb-fe/src/components/Home/HeroSection/Header/NavRadio/Online.jsx
  FE/airbnb-fe/src/components/Home/HeroSection/Header/NavRadio/Room.jsx
  FE/airbnb-fe/src/components/Home/HeroSection/Header/index.jsx
  FE/airbnb-fe/src/components/Reservation/ReservationHeader/index.jsx
  FE/airbnb-fe/src/components/Reservation/index.jsx
Labels: enhancement, 프론트엔드
